### ISSUE TITLE
Blank Window on Ubuntu 24.04 and Ubuntu 22.04

### ISSUE THREAD

**Issue by hrzlgnm** [hrzlgnm/mdns-browser#354]
* Probably caused by an Ubuntu update on 2024-09-10 according to https://github.com/tauri-apps/tauri/issues/10626
Downgarding "those" updates makes the issue go away

Upstream issue: https://bugs.launchpad.net/ubuntu/+source/webkit2gtk/+bug/2081166

Updates:
- workaround for Ubuntu 24.04: https://github.com/hrzlgnm/mdns-browser/issues/354#issuecomment-2404750185
- workaround for Ubuntu 22.04: use a tauri-1.0 based build from a release < 0.8.x: https://github.com/hrzlgnm/mdns-browser/releases/tag/mdns-browser-v0.7.14

**Comment by hrzlgnm** [comment]
On Ubuntu 24.04 I'm using the following workaround, by downgrading and setting the respective packages on hold:

note: the -dev packages may not be required if not installed.
```
sudo apt install libwebkit2gtk-4.1-0=2.44.0-2 libjavascriptcoregtk-4.1-0=2.44.0-2 gir1.2-javascriptcoregtk-4.1=2.44.0-2 gir1.2-webkit2-4.1=2.44.0-2 libjavascriptcoregtk-4.1-dev=2.44.0-2 libwebkit2gtk-4.1-dev=2.44.0-2
sudo apt-mark hold libwebkit2gtk-4.1-0 libjavascriptcoregtk-4.1-0 gir1.2-javascriptcoregtk-4.1 gir1.2-webkit2-4.1 libjavascriptcoregtk-4.1-dev ibwebkit2gtk-4.1-dev
```

**Comment by tetuaoro** [comment]
> sudo apt install libwebkit2gtk-4.1-0=2.44.0-2 libjavascriptcoregtk-4.1-0=2.44.0-2 gir1.2-javascriptcoregtk-4.1=2.44.0-2 gir1.2-webkit2-4.1=2.44.0-2 libjavascriptcoregtk-4.1-dev=2.44.0-2 libwebkit2gtk-4.1-dev=2.44.0-2
> sudo apt-mark hold libwebkit2gtk-4.1-0 libjavascriptcoregtk-4.1-0 gir1.2-javascriptcoregtk-4.1 gir1.2-webkit2-4.1 libjavascriptcoregtk-4.1-dev ibwebkit2gtk-4.1-dev
> ```

Thank you. It works for me.

**Comment by duncanawoods** [comment]
@hrzlgnm can you sanity check my failed attempt for 22.04?

It doesn't appear that `2.44.0-2` exist in apt:

```
►apt-cache madison libwebkit2gtk-4.1-0

libwebkit2gtk-4.1-0 | 2.44.3-0ubuntu0.22.04.1 | http://gb.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
libwebkit2gtk-4.1-0 | 2.44.3-0ubuntu0.22.04.1 | http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
libwebkit2gtk-4.1-0 | 2.36.0-2ubuntu1 | http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

So I have tried using `2.36.0-2ubuntu1`

```
sudo apt install libwebkit2gtk-4.1-0=2.36.0-2ubuntu1 libjavascriptcoregtk-4.1-0=2.36.0-2ubuntu1 gir1.2-javascriptcoregtk-4.1=2.36.0-2ubuntu1 gir1.2-webkit2-4.1=2.36.0-2ubuntu1 libjavascriptcoregtk-4.1-dev=2.36.0-2ubuntu1 libwebkit2gtk-4.1-dev=2.36.0-2ubuntu1
```

But it looks like some dep of tauri has a ">=2.38" requirement...

```
   Compiling gdkwayland-sys v0.18.0
The following warnings were emitted during compilation:

warning: javascriptcore-rs-sys@1.1.1: 

error: failed to run custom build command for `javascriptcore-rs-sys v1.1.1`

Caused by:
  process didn't exit successfully: `/home/duncan/Projects/ruddy/target/debug/build/javascriptcore-rs-sys-c750441f8b3153bb/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=JAVASCRIPTCOREGTK_4.1_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags javascriptcoregtk-4.1 javascriptcoregtk-4.1 >= 2.38

  The system library `javascriptcoregtk-4.1` required by crate `javascriptcore-rs-sys` was not found.
  The file `javascriptcoregtk-4.1.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `javascriptcoregtk-4.1.pc`.

warning: build failed, waiting for other jobs to finish...
```

**Comment by hrzlgnm** [comment]
> @hrzlgnm can you sanity check my failed attempt for 22.04?
> 
> It doesn't appear that `2.44.0-2` exists in apt:
> 
> ```
> ►apt-cache madison libwebkit2gtk-4.1-0
> 
> libwebkit2gtk-4.1-0 | 2.44.3-0ubuntu0.22.04.1 | http://gb.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
> libwebkit2gtk-4.1-0 | 2.44.3-0ubuntu0.22.04.1 | http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
> libwebkit2gtk-4.1-0 | 2.36.0-2ubuntu1 | http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
> ```
> 
> So I have tried using `2.36.0-2ubuntu1`
> 
> ```
> sudo apt install libwebkit2gtk-4.1-0=2.36.0-2ubuntu1 libjavascriptcoregtk-4.1-0=2.36.0-2ubuntu1 gir1.2-javascriptcoregtk-4.1=2.36.0-2ubuntu1 gir1.2-webkit2-4.1=2.36.0-2ubuntu1 libjavascriptcoregtk-4.1-dev=2.36.0-2ubuntu1 libwebkit2gtk-4.1-dev=2.36.0-2ubuntu1
> ```
> 
> But it looks like some dep of tauri has a ">=2.38" requirement...
> 
> ```
>    Compiling gdkwayland-sys v0.18.0
> The following warnings were emitted during compilation:
> 
> warning: javascriptcore-rs-sys@1.1.1: 
> 
> error: failed to run custom build command for `javascriptcore-rs-sys v1.1.1`
> 
> Caused by:
>   process didn't exit successfully: `/home/duncan/Projects/ruddy/target/debug/build/javascriptcore-rs-sys-c750441f8b3153bb/build-script-build` (exit status: 1)
>   --- stdout
>   cargo:rerun-if-env-changed=JAVASCRIPTCOREGTK_4.1_NO_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:warning=
>   pkg-config exited with status code 1
>   > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags javascriptcoregtk-4.1 javascriptcoregtk-4.1 >= 2.38
> 
>   The system library `javascriptcoregtk-4.1` required by crate `javascriptcore-rs-sys` was not found.
>   The file `javascriptcoregtk-4.1.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
>   The PKG_CONFIG_PATH environment variable is not set.
> 
>   HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `javascriptcoregtk-4.1.pc`.
> 
> warning: build failed, waiting for other jobs to finish...
> ```

As I stated, the workaround I'm using is for Ubuntu 24.04. And I'm using that workaround to run the app from this repository on my Laptop at work. I got fed up at some timepoint with Ubuntu and stopped using it on private desktop computers and switched to Void Linux. But I'll try to workout something on my Pop!Os which should the most similar I have to a Ubuntu 22.04.

**Comment by hrzlgnm** [comment]
@duncanawoods I tried to downgrade libwebkit2gkt on my Pop!OS VM , but unfortunately that also breaks the compatiblity with tauri-2.0 apps due to symbol not being present:
```
✘ valeni@pop-os$ mdns-browser 
mdns-browser: symbol lookup error: mdns-browser: undefined symbol: webkit_uri_scheme_request_get_http_body
```
I guess there is nothing I can do for Ubuntu 22.04 regardin this. I also created an account especially for saying that I'm also affected in https://bugs.launchpad.net/ubuntu/+source/webkit2gtk/+bug/2081166, to put more awarenes on that upstream issue.

**Comment by tetuaoro** [comment]
Hi, can you post your trunk version ? After upgrading trunk to `0.21.1`, the blank screen appears again and disappears when I downgrad trunk to `0.20.3`.

**Comment by hrzlgnm** [comment]
> Hi, can you post your trunk version ? After upgrading trunk to `0.21.1`, the blank screen appears again and disappears when I downgrad trunk to `0.20.3`.

I recently updated to `0.21.1` to, but the latest release which works on ubuntu was build using `0.20.3`.

**Comment by duncanawoods** [comment]
> but unfortunately that also breaks the compatiblity with tauri-2.0 apps due a to symbol not being present:

Yeah I saw that missing symbol when I just did a partial build. When I did clean build of a complete workspace then it failed earlier.

Thanks for giving it a go :heart:

**Comment by vb-linetco** [comment]
> sudo apt-mark hold libwebkit2gtk-4.1-0 libjavascriptcoregtk-4.1-0 gir1.2-javascriptcoregtk-4.1 gir1.2-webkit2-4.1 libjavascriptcoregtk-4.1-dev ibwebkit2gtk-4.1-dev

Whoever used the workaround for Ubuntu 24.04, here is how to undo it:
```console
sudo apt-mark unhold libwebkit2gtk-4.1-0 libjavascriptcoregtk-4.1-0 gir1.2-javascriptcoregtk-4.1 gir1.2-webkit2-4.1 libjavascriptcoregtk-4.1-dev ibwebkit2gtk-4.1-dev
```
to revert the change. Then try updating again. That should fix the issue.

An update has been released on Ubuntu today and the upstream issue is closed.

**Comment by hrzlgnm** [comment]
Fixed in upstream: https://bugs.launchpad.net/ubuntu/+source/webkit2gtk/+bug/2081166

**Comment by hrzlgnm** [comment]
> Hi, can you post your trunk version ? After upgrading trunk to `0.21.1`, the blank screen appears again and disappears when I downgrad trunk to `0.20.3`.

Thank you for the pointer. I was also debugging loading issues recently.

I noticed that trunk `0.21.1` somehow bundles some ancient js code from tauri 1 somehow when used together with tauri-sys v2. That leads issue during loading of the app as sometimes the ancient code is triggered instead of the actual v2 code.

Downgrading to `0.20.3` again.

**Comment by hrzlgnm** [comment]
> @tetuaoro
> 
> > Hi, can you post your trunk version ? After upgrading trunk to `0.21.1`, the blank screen appears again and disappears when I downgrad trunk to `0.20.3`.
> 
> Thank you for the pointer. I was also debugging loading issues recently.
> 
> I noticed that trunk `0.21.1` somehow bundles some ancient js code from tauri v1 when used together with tauri-sys v2. That leads issue during loading of the app as sometimes the ancient code is triggered instead of the actual v2 code.
> 
> Downgrading to `0.20.3` again.

Hmm, after digging further, I could not observe this behavior anymore. I was also using tauri-sys while still using tauri v1. Prehaps some old stuff piled up in my cargo cache directory. After cleaning it up fully the observed issue with the old js files from tauri also vanished with trunk 0.21.1 and does not occur anymore.
